### ISSUE TITLE
multiple ctrl-k's only saves the last one to the clipboard

### ISSUE THREAD

**Issue by alanhoyle** [mndrix/atom-emacs-core-keys#7]
The regular behavior for emacs would be that multiple "kill" commands in a row would add to a kill buffer, so that the next "yank" command would paste all of the previous kill buffer back into place.  Would it be possible to implement that here without trying to implement a full kill-ring?

**Comment by mndrix** [comment]
It's a good idea.  I've tried several times to implement something similar using just Atom keybindings configuration, but always come up short.  As far as I can tell, it would require writing CoffeeScript.  Since that's [off limits for this package](https://github.com/mndrix/atom-emacs-core-keys/tree/2db4b5537270b245930aa80ae1195ad83997644e#why), I haven't added it.

I think it'd be nice to have an emacs-core-kill package which does just what you suggest without all the complexity of a full kill-ring.
